### ISSUE TITLE
"Socket operation on non-socket" error under a non-monadic, threaded proxy

### ISSUE THREAD

**Issue by kayceesrk** [twittner/zeromq-haskell#57]
Hello,

When starting a non-monadic 0MQ proxy compiled with -threaded flag, I get the following error: 
  
    { errno = 38, source = "c_zmq_proxy", message = "Socket operation on non-socket" }

The error does not occur if the -threaded flag is elided. Also, the error does not occur when a similar code is run under the ZMQ monad (both threaded and non-threaded). Here is the code snippet that I'm using for testing.

```haskell
-- testProxy.hs

#ifdef MONADIC
import System.ZMQ4.Monadic
#else
import System.ZMQ4
#endif

main = core

#ifdef MONADIC
core = runZMQ $ do
  r <- socket Router
  bind r "inproc://A"
  d <- socket Dealer
  bind d "inproc://B"
  proxy r d Nothing
#else
core = do
  ctxt <- context
  r <- socket ctxt Router
  bind r "inproc://A"
  d <- socket ctxt Dealer
  bind d "inproc://B"
  proxy r d Nothing
#endif
```

Here is my output under different flags:

    kc:tests chandras$ rm testProxy
    kc:tests chandras$ ghc -cpp -threaded -DMONADIC testProxy.hs
    [1 of 1] Compiling Main             ( testProxy.hs, testProxy.o ) [flags changed]
    Linking testProxy ...
    kc:tests chandras$ ./testProxy
    ^C
    kc:tests chandras$ rm testProxy
    kc:tests chandras$ ghc -cpp -threaded testProxy.hs
    [1 of 1] Compiling Main             ( testProxy.hs, testProxy.o ) [flags changed]
    Linking testProxy ...
    kc:tests chandras$ ./testProxy
    testProxy: ZMQError { errno = 38, source = "c_zmq_proxy", message = "Socket operation on non-socket" }
    kc:tests chandras$ rm testProxy
    kc:tests chandras$ ghc -cpp testProxy.hs
    Linking testProxy ...
    kc:tests chandras$ ./testProxy
    ^C^C
    kc:tests chandras$ 

Thanks
KC

**Comment by twittner** [comment]
I think my previous account was not correct. The actual reason why the non-monadic version errors is because the garbage collector finalises the sockets soon after control reaches the `proxy`-call because they are no longer reachable. The finaliser concurrently closes the sockets, hence the error. The monadic version has implicit `close` statements pending which prevent garbage collection of `d` and `r`. You could add `close r` and `close d` after `proxy r d Nothing` and it will work fine.

**Comment by kayceesrk** [comment]
Thanks for the clarification. This makes sense. So the correct method to invoke `proxy` is to follow it up with the necessary close socket calls.

**Comment by twittner** [comment]
Yes, though ideally the non-monadic version would use `withContext` and `withSocket` for proper resource cleanup, e.g.

```haskell
main =
  withContext $ \ctx ->
    withSocket ctx Router $ \r ->
    withSocket ctx Dealer $ \d -> do
      bind r "inproc://A"
      bind d "inproc://B"
      proxy r d Nothing
```
