### ISSUE TITLE
Ctrl-C does not halt the interrupt example

### ISSUE THREAD

**Issue by patrickboe** [twittner/zeromq-haskell#63]
I am unclear whether this is a bug in [the Haskell interrupt example in the zguide](https://github.com/imatix/zguide/blob/master/examples/Haskell/interrupt.hs), a bug in the implementation of `receive`, or simply a misunderstanding on my part, but I was expecting to be able to run the interrupt example and then see an orderly exit in response to Ctrl-C.  Instead, I must kill -9 in order to get control back in the shell.  If this is a bug in `receive`, it also makes me worry about anything that receives within an `async` context - do resources in the child threads get disposed?

From the 0MQ Guide:

> ... The interrupt will affect ZeroMQ calls as follows:

> If your code is blocking in a blocking call (sending a message, receiving a message, or polling), then when a signal arrives, the call will return with EINTR.
> ...

Receive seems to block without returning an EINTR-like value, even in the presence of a SIGINT.  This looks like a bug to me, as it differs from the documented description.

I am running Debian Wheezy GNU/Linux with libzmq v4 installed.

I am happy to work up and contribute a bugfix patch for this if it is indeed a bug and not just a misunderstanding on my part.

**Comment by twittner** [comment]
The code you linked to catches `SIGINT` and `SIGTERM` and assumes that `receive` would be interrupted. This is based on a misunderstanding of how `zeromq-haskell` works. We utilise GHC's I/O manager to wait for data to become available for read (cf. http://hackage.haskell.org/package/base-4.7.0.2/docs/Control-Concurrent.html#v:threadWaitRead), i.e. when executing the example, you are not blocked in receive at all.

**Comment by patrickboe** [comment]
When you say "This is based on a misunderstanding," are you saying the example is bad or that I'm misunderstanding the example?

**Comment by patrickboe** [comment]
Also, your link to the control-concurrent doc says that threadWaitRead does block the current thread, so if receive uses it, receive would block as well, right?

**Comment by twittner** [comment]
> are you saying the example is bad or that I'm misunderstanding the example?

The example is based on a misunderstanding.

> control-concurrent doc says that threadWaitRead does block the current thread

Yes, it blocks the current _GHC thread_ (which is not a native thread). What I meant is that you are not blocked in `zmq_recvmsg`.
