### ISSUE TITLE
Possible to include C source with zeromq4-haskell?

### ISSUE THREAD

**Issue by gibiansky** [twittner/zeromq-haskell#64]
Right now, to install `zeromq-haskell`, you must have installed the C library, whether through `brew` on OS X or through other package managers on Linux. 

Is it possible to just ship the C source of ZeroMQ with `zeromq-haskell` to reduce the installation difficulties? It would be very nice if you could install `zeromq-haskell` with *just* `cabal install zeromq4-haskell`, rather than needing to fiddle with libraries.

(Note that I have not personally looked into the feasability of this, which is why I am asking – I have just realized that it would be nice and would ease the installation of `ihaskell` for many people.)

**Comment by twittner** [comment]
What would be the target location of the embedded zeromq library? You do not want to interfere with the package manager, which implies a non-standard location which may require a custom `LD_LIBRARY_PATH`. Would that still be a win for you clients?

How about library updates? Do we have to release a new zeromq4-haskell version whenever a patch release of zeromq is made even though the binding does not require changes? This would require more frequent releases and more updates for clients than necessary.

**Comment by gibiansky** [comment]
Oh, library updates are a good point. Oh well. Though, I personally don't know how often zeromq4 library patches are released. 

As for the target location, I was just thinking of static linking, sort of like what the [picosat](https://github.com/sdiehl/haskell-picosat) library does. But perhaps ZeroMQ is too big to include like that?

Anyway, I am definitely not sure whether a) this is really an improvement or b) this is easy. I just saw that some Haskell packages go the way of just including the relevant C source and compiling it, and wondered whether it might be a good idea for zeromq – would certainly ease installation of the package (maybe). Sounds like there are fairly good arguments against it though.
