### ISSUE TITLE
Not thread safe?

### ISSUE THREAD

**Issue by mitchellwrosen** [twittner/zeromq-haskell#66]
ZMQ sockets are not thread safe, but it looks like you can spawn a thread via `async`, share a socket with it, and it's up to the Haskell runtime whether or not that computation occurs on the same OS thread.

**Comment by mitchellwrosen** [comment]
Just a thought - this may be as simple as changing
```haskell
    liftIO . A.async $ (runReaderT (_unzmq z) e) `E.finally` term e
```
to
```haskell
    liftIO . A.asyncBound $ (runReaderT (_unzmq z) e) `E.finally` term e
```
in `System.ZMQ4.Monadic.async`

**Comment by twittner** [comment]
Yes, 0MQ sockets are not thread-safe. However I do not think it is required to always access them from the same OS thread. It should be sufficient to guarantee single-threaded access and proper read/write memory barriers to ensure visibility and ordering when accessing from different threads. As far as the RTS scheduler is concerned I expected it to ensure visibility and ordering when migrating OS threads. Do you say it doesn't?

**Comment by mitchellwrosen** [comment]
From the docs:

> Individual ØMQ sockets are not thread safe except in the case where full memory barriers are issued when migrating a socket from one thread to another. In practice this means applications can create a socket in one thread with zmq_socket() and then pass it to a newly created thread as part of thread initialization, for example via a structure passed as an argument to pthread_create().

I suppose you're right.
