### ISSUE TITLE
Does not work with zeromq-4.1.x

### ISSUE THREAD

**Issue by WraithM** [twittner/zeromq-haskell#69]
I upgraded zeromq to 4.1.2 (I assume this issue is the same with 4.1.1).

`error while loading shared libraries: libzmq.so.4: cannot open shared object file: No such file or directory`

I checked /usr/lib, and I found libzmq.so.5 instead of libzmq.so.4. I downgraded to zeromq 4.0.5 and everything worked.

Maybe I just need to recompile with the newest version of zeromq installed, but it looks like there were some API changes to zeromq, hence the version bump on their end.

**Comment by twittner** [comment]
> Maybe I just need to recompile [...]

Would you mind trying that?

**Comment by twittner** [comment]
Closing since compiling against 4.1.2 works fine for me. Feel free to reopen if you still have issues.

**Comment by WraithM** [comment]
@twittner I'm sorry for not replying to you! I was moving this weekend. I recompiled with 4.1.2, and everything worked fine. Thanks!
