### ISSUE TITLE
cross-compile Base.hsc - directive alignment cannot be handled in cross-compilation mode

### ISSUE THREAD

**Issue by ef-ge** [twittner/zeromq-haskell#71]
Hi,

is there a workaround to cross-compile (host is x86, target is x86_64) it? Currently it breaks with:
> $ runghc Setup build
Building zeromq4-haskell-0.6.3...
Preprocessing library zeromq4-haskell-0.6.3...
src/System/ZMQ4/Internal/Base.hsc:28 directive alignment cannot be handled in cross-compilation mode

I'm realy not an haskell expert, so if you have any hints please let me know.

Thanks in advance!

**Comment by twittner** [comment]
AFAIK [hsc does not support certain constructs when cross-compiling](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/hsc2hs.html#hsc2hs_cross). You could edit the `Storable` instances in `Base.hsc` and enter the values for `alignment` directly, but you need to determine the correct values from your target system.

**Comment by ef-ge** [comment]
Thank you twittner for the reply!

So what i have done now is that i wrote a small C-Application, cross-compiled it with target-gcc and executed it on target:
```C
#include <stdio.h>
#include <zmq.h>

int main() {
	printf("zmq_msg_t: %lu\n",
		(unsigned long)offsetof(struct {char x__; zmq_msg_t (y__); }, y__));
	printf("zmq_pollitem_t: %lu\n",
		(unsigned long)offsetof(struct {char x__; zmq_pollitem_t (y__); }, y__));
	printf("zmq_event_t: %lu\n",
		(unsigned long)offsetof(struct {char x__; zmq_event_t (y__); }, y__));

	return 0;
}
```

It prints out:

_zmq_msg_t: 1_
_zmq_pollitem_t: 8_
_zmq_event_t: 4_

Then i used the output to replace the _alignment_ values and comment out the _#let alignment..._ line.

```Diff
diff --git a/src/System/ZMQ4/Internal/Base.hsc b/src/System/ZMQ4/Internal/Base.hsc
index a6823c7..0f05579 100644
--- a/src/System/ZMQ4/Internal/Base.hsc
+++ b/src/System/ZMQ4/Internal/Base.hsc
@@ -25,7 +25,7 @@ newtype ZMQMsg = ZMQMsg
   } deriving (Eq, Ord)
 
 instance Storable ZMQMsg where
-    alignment _        = #{alignment zmq_msg_t}
+    alignment _        = 1 :: Int
     sizeOf    _        = #{size zmq_msg_t}
     peek p             = ZMQMsg <$> #{peek zmq_msg_t, _} p
     poke p (ZMQMsg c)  = #{poke zmq_msg_t, _} p c
@@ -41,7 +41,7 @@ data ZMQPoll = ZMQPoll
     }
 
 instance Storable ZMQPoll where
-    alignment _ = #{alignment zmq_pollitem_t}
+    alignment _ = 8 :: Int
     sizeOf    _ = #{size zmq_pollitem_t}
     peek p = do
         s  <- #{peek zmq_pollitem_t, socket} p
@@ -60,7 +60,7 @@ type ZMQCtx     = Ptr ()
 type ZMQSocket  = Ptr ()
 type ZMQPollPtr = Ptr ZMQPoll
 
-#let alignment t = "%lu", (unsigned long)offsetof(struct {char x__; t (y__); }, y__)
+-- #let alignment t = "%lu", (unsigned long)offsetof(struct {char x__; t (y__); }, y__)
 
 -----------------------------------------------------------------------------
 -- Socket Types
@@ -187,7 +187,7 @@ data ZMQEvent = ZMQEvent
 
 #if ZMQ_VERSION < 40100
 instance Storable ZMQEvent where
-    alignment _ = #{alignment zmq_event_t}
+    alignment _ = 4 :: Int
     sizeOf    _ = #{size zmq_event_t}
     peek e = ZMQEvent
         <$> (ZMQEventType <$> #{peek zmq_event_t, event} e)
```

It builds fine now. Hope the used _alignment_ replacement is correct and this helps other people to cross-compile the package without deeper knowledge about haskell.
