### ISSUE TITLE
Where is zmq_msg_more?

### ISSUE THREAD

**Issue by Eilie** [twittner/zeromq-haskell#72]
How to receive multipart message part by part?

**Comment by twittner** [comment]
[`receiveMulti`](http://hackage.haskell.org/package/zeromq4-haskell-0.6.3/docs/System-ZMQ4.html#v:receiveMulti) does not work for you? Did you see [`moreToReceive`](http://hackage.haskell.org/package/zeromq4-haskell-0.6.3/docs/System-ZMQ4.html#v:moreToReceive)?

**Comment by Eilie** [comment]
@twittner, `receiveMulti` exactly want I wanted, thank you!
