### ISSUE TITLE
The pkg-config package 'libzmq' version >=3.2 && <4.0 is required but it could not be found.

### ISSUE THREAD

**Issue by LovelyYanki** [twittner/zeromq-haskell#73]
Configuring zeromq3-haskell-0.5.2...
cabal: The pkg-config package 'libzmq' version >=3.2 && <4.0 is required but
it could not be found.
Failed to install zeromq3-haskell-0.5.2
cabal: Error: some packages failed to install:
zeromq3-haskell-0.5.2 failed during the configure step. The exception was:
ExitFailure 1
martin@ubuntu:~$ cabal sandbox init
Writing a default package environment file to
/home/martin/cabal.sandbox.config
Using an existing sandbox located at /home/martin/.cabal-sandbox
martin@ubuntu:~$ cabal update
Downloading the latest package list from hackage.haskell.org
Skipping download: Local and remote files match.
martin@ubuntu:~$ cabal install -j
cabal: Error reading local package.
Couldn't find .cabal file in: .

martin@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

**Comment by twittner** [comment]
Do you have `libzmq` installed? It seems you are on Ubuntu 14.04. I haven't yet fixed #53 which you may run into once you installed `libzmq3-dev` on your machine. If you do, could you edit zeromq3-haskell.cabal and change [line 50](https://github.com/twittner/zeromq-haskell/blob/zeromq-3/zeromq3-haskell.cabal#L50) to `pkgconfig-depends: libzmq >= 3.2 && < 4.1`? Alternatively you may want to try zeromq4-haskell.

**Comment by LovelyYanki** [comment]
can not find  libzmq3-dev or  libzmq when install with cabal install and cabal update

martin@ubuntu:~/mal$ cabal install libzmq3-dev
cabal: There is no package named 'libzmq3-dev'.
You may need to run 'cabal update' to get the latest list of available
packages.
martin@ubuntu:~/mal$ cabal update
Downloading the latest package list from hackage.haskell.org
martin@ubuntu:~/mal$ cabal install libzmq3-dev
cabal: There is no package named 'libzmq3-dev'.
You may need to run 'cabal update' to get the latest list of available
packages.
martin@ubuntu:~/mal$ cabal install libzmq4-dev
cabal: There is no package named 'libzmq4-dev'.
You may need to run 'cabal update' to get the latest list of available
packages.
martin@ubuntu:~/mal$ cabal install zeromq4-haskell
Resolving dependencies...
Downloading zeromq4-haskell-0.6.3...
Configuring zeromq4-haskell-0.6.3...
cabal: The pkg-config package 'libzmq' version >=4.0 && <5.0 is required but
it could not be found.
Failed to install zeromq4-haskell-0.6.3
cabal: Error: some packages failed to install:
zeromq4-haskell-0.6.3 failed during the configure step. The exception was:
ExitFailure 1
martin@ubuntu:~/mal$ cabal install libzmq
cabal: There is no package named 'libzmq'.
You may need to run 'cabal update' to get the latest list of available
packages.
martin@ubuntu:~/mal$ cabal install
cabal: Error reading local package.
Couldn't find .cabal file in: .
martin@ubuntu:~/mal$ cabal update
Downloading the latest package list from hackage.haskell.org
Skipping download: Local and remote files match.
martin@ubuntu:~/mal$ cabal install libzmq
cabal: There is no package named 'libzmq'.
You may need to run 'cabal update' to get the latest list of available
packages.

**Comment by twittner** [comment]
zeromq-haskell is an FFI binding to 0MQ, hence you need to have 0MQ installed before compiling zeromq-haskell. Ubuntu provides a package (see http://packages.ubuntu.com/trusty/libzmq3-dev) which can be installed via `apt-get`. See http://zeromq.org/intro:get-the-software for details.

**Comment by LovelyYanki** [comment]
i succeed to install libzmq3-dev, i can not find zeromq3-haskell.cabal , where it is?

**Comment by LovelyYanki** [comment]
succeed to install zeromq4-haskell-0.6.3. solved.
